#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

HOSTNAME=$(hostname)
FLAKE_TARGET="homeConfigurations.${HOSTNAME}.activationPackage"

echo "${YELLOW}Starting build...${NC}"
RESULT=$(nix --extra-experimental-features 'nix-command flakes' build ".#${FLAKE_TARGET}" --no-link --print-out-paths "$@")

echo "${YELLOW}Switching to new generation...${NC}"
HOME_MANAGER_BACKUP_EXT="hm-backup" "${RESULT}/activate"

echo "${GREEN}Switch to new generation complete!${NC}"
